---
abstract: ~
author:
  - 'Steve Price <sdprice@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Framework
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Spec: 0.80
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
